/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CityStation {
    }
    interface FirstComponent {
        "sentence": string;
    }
    interface MeteoStation {
        "city": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SnackBar {
        "button": string;
        "open": () => Promise<void>;
        "sentence": string;
        "visible": boolean;
    }
}
export interface CityStationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCityStationElement;
}
export interface MeteoStationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMeteoStationElement;
}
declare global {
    interface HTMLCityStationElement extends Components.CityStation, HTMLStencilElement {
    }
    var HTMLCityStationElement: {
        prototype: HTMLCityStationElement;
        new (): HTMLCityStationElement;
    };
    interface HTMLFirstComponentElement extends Components.FirstComponent, HTMLStencilElement {
    }
    var HTMLFirstComponentElement: {
        prototype: HTMLFirstComponentElement;
        new (): HTMLFirstComponentElement;
    };
    interface HTMLMeteoStationElement extends Components.MeteoStation, HTMLStencilElement {
    }
    var HTMLMeteoStationElement: {
        prototype: HTMLMeteoStationElement;
        new (): HTMLMeteoStationElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSnackBarElement extends Components.SnackBar, HTMLStencilElement {
    }
    var HTMLSnackBarElement: {
        prototype: HTMLSnackBarElement;
        new (): HTMLSnackBarElement;
    };
    interface HTMLElementTagNameMap {
        "city-station": HTMLCityStationElement;
        "first-component": HTMLFirstComponentElement;
        "meteo-station": HTMLMeteoStationElement;
        "my-component": HTMLMyComponentElement;
        "snack-bar": HTMLSnackBarElement;
    }
}
declare namespace LocalJSX {
    interface CityStation {
        "onCitySelected"?: (event: CityStationCustomEvent<string>) => void;
    }
    interface FirstComponent {
        "sentence"?: string;
    }
    interface MeteoStation {
        "city"?: string;
        "onCitySelected"?: (event: MeteoStationCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SnackBar {
        "button"?: string;
        "sentence"?: string;
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "city-station": CityStation;
        "first-component": FirstComponent;
        "meteo-station": MeteoStation;
        "my-component": MyComponent;
        "snack-bar": SnackBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "city-station": LocalJSX.CityStation & JSXBase.HTMLAttributes<HTMLCityStationElement>;
            "first-component": LocalJSX.FirstComponent & JSXBase.HTMLAttributes<HTMLFirstComponentElement>;
            "meteo-station": LocalJSX.MeteoStation & JSXBase.HTMLAttributes<HTMLMeteoStationElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "snack-bar": LocalJSX.SnackBar & JSXBase.HTMLAttributes<HTMLSnackBarElement>;
        }
    }
}
